api/urls.py
from django.urls import path, include
from api.views import postview, rankview, recommended, replay
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register(r'posts', postview.PostSet)
router.register(r'ranks', rankview.RankSet)
router.register(r'recommended', recommended.RecommendedSet)
router.register(r'ReviewPosts', postview.PostSetOrderForReview)

router.register(r'reply', replay.ReplySet)

app_name = 'api'
urlpatterns = [
    path('', include(router.urls)),
]

app/urls.py
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    # 首页
    path('', views.index, name='index'),
    # 登陆界面
    path('login/', views.login, name='login'),
    # 注册界面
    path('signup/', views.signup, name='signup'),
    # 注册用户
    path('register/', views.register, name='register'),
    # 注销
    path('logout/', views.logout, name='logout'),
    # 进入修改个人资料界面
    path('change/', views.to_change, name='change'),
    # 修改个人资料
    path('modify/', views.modify, name='modify'),
    # 进入发帖界面
    path('posting/', views.posting, name='posting'),
    # 用户展示
    path('showuser/',views.show_user, name='showuser'),
    # 创建板块
    path('create_plate/', views.create_plate, name='create_plate'),
    # 添加板块
    path('add_plate/', views.add_plate, name='add_plate'),
    # 创建标签
    path('create_tag/', views.create_tag, name='create_tag'),
    # 添加标签
    path('add_tag/', views.add_tag, name='add_tag'),
    # 添加帖子
    path('add_post/', views.add_post, name='add_post'),
    # 帖子展示
    path('show_post/', views.post, name='show_post'),
    # 添加点赞
    path('add_like/', views.add_like, name='add_like'),
    # 取消点赞
    path('reduce_like/', views.reduce_like, name='reduce_like'),
    # 添加评论
    path('add_review/', views.add_review, name='add_review'),
    # 展示帖子列表
    path('show_posts/', views.show_posts, name='show_posts'),
    # 动态登录
    path('dynamic_login/', views.dynamic_login, name='dynamic_login'),
    # 获取用户
    path('getuser/', views.get_user, name="get_user"),
    # 发送邮件
    path('sendmail/', views.sendmail, name="sendmail"),
    # 查询
    path('search/', views.search, name='search'),
    # 上传图片
    path('upload_image/', views.upload_image, name="uploadimage"),
    # 最新
    path('latest/', views.latest, name='latest'),
    # 添加回复
    path('addreply/', views.add_replay, name='addreplay'),
    # 修改密码
    path('changepassword/', views.change_password, name='changepassword'),
]

bbs/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve

import xadmin
from bbs.settings import MEDIA_ROOT, DEBUG


urlpatterns = [
    path('admin/', admin.site.urls),
    path('xadmin/', xadmin.site.urls),
    path('api/', include('api.urls')),
    path('', include('app.urls')),

    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT}),

]

#
if not DEBUG:
    from bbs.settings import STATIC_ROOT
    urlpatterns.append(re_path(r'^static/(?P<path>.*)$', serve, {'document_root': STATIC_ROOT}))

api/views/postview.py
from django.shortcuts import render
from django.http import HttpResponse,JsonResponse
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework.parsers import JSONParser
from app.models import *
from api.serializers import PostSerializer
from rest_framework import status, generics, viewsets


class PostSet(viewsets.ReadOnlyModelViewSet):
    queryset = Post.objects.all().order_by('-create_time')
    serializer_class = PostSerializer


class PostSetOrderForReview(viewsets.ReadOnlyModelViewSet):
    queryset = Post.objects.all().order_by("-reviews")
    serializer_class = PostSerializer


class PostList(generics.ListAPIView):
    queryset = Post.objects.all().order_by('-create_time')
    serializer_class = PostSerializer


class PostDetail(generics.RetrieveAPIView):
    queryset = Post.objects.all().order_by('-create_time')
    serializer_class = PostSerializer
# Create your views here.
@api_view(['GET', ])
def post_list(request, format=None):
    if request.method == "GET":
        posts = Post.objects.all().order_by('-create_time')
        try:
            if request.GET.get('order'):
                posts = Post.objects.all().order_by("-reviews")
        except:
            pass
        try:
            num = request.GET.get('num')
            posts = posts[0:int(num)]
        except:
            pass
        serializer = PostSerializer(posts, many=True)
        return Response(serializer.data)

    else:
        return Response(status=status.HTTP_404_NOT_FOUND)


@api_view(["GET", ])
def post_detail(request, pk, format=None):
    try:
        post = Post.objects.get(pk=pk)
    except:
        return Response(status=status.HTTP_404_NOT_FOUND)

    if request.method == "GET":
        serializer = PostSerializer(post)
        return Response(serializer.data)
    else:
        return Response(status=status.HTTP_404_NOT_FOUND)

templates/form/loginform.html
<form action="{% url 'app:login' %}" method="post">{% csrf_token %}
    <div class="form-group form-style">
        <div class="input-group">
            <div class="input-group-addon">邮 箱</div>
            <input type="text" class="form-control" id="email" name="email" placeholder="请输入邮箱"/>
        </div>
    </div>
    <div class="form-group form-style">
        <div class="input-group">
            <div class="input-group-addon">密 码</div>
            <input type="password" class="form-control" id="password" name="password" placeholder="请输入密码"/>
        </div>
    </div>
    <div class="form-group form-style">
        <a href="{% url 'app:changepassword' %}" class="btn btn-link col-sm-12 text-center">忘记密码？</a>

    </div>
    <div class="form-group form-style">
        <input type="button" value="登录" class="btn btn-primary col-sm-12" id="submit">
        <input type="submit" class="hidden" id="login">
    </div>
    <div class="form-group form-style">
        <a href="{% url 'app:dynamic_login' %}" class="btn btn-link col-sm-12 text-center">验证码登录</a>
    </div>

    <div class="form-group form-style">
        <a href="{% url 'app:signup' %}" class="btn btn-link col-sm-12 text-center">现在注册</a>
    </div>
</form>

templates/form/plateform.html
<form action="" method="post" onsubmit="">{% csrf_token %}
    <div class="form-group form-style">
        <label for="plate_name">板块名</label>
        <input type="text" class="form-control" id="plate_name" name="plate_name" placeholder="请输入您创建的板块名"/>
    </div>
    <div class="form-group form-style">
        <label for="description">描述你创建的板块</label>
        <textarea class="form-control" id="description" name="description" rows="8"></textarea>
    </div>
    <div class="form-group form-style">
        <input type="button" id="submit" value="提交" class="btn btn-block col-sm-12">
    </div>
</form>
<script>
    $(document).ready(function () {
        $('#submit').click(function () {
            $.ajaxSetup({
                data: {csrfmiddlewaretoken: '{{ csrf_token }}'},
            });

            $.ajax({
                url: "{% url 'app:add_plate' %}",
                data: {
                    "plate_name": $("#plate_name").val(),
                    'description': $("#description").val(),
                },
                type: "POST",
                success: function (data) {
                    if (data === '-1') {
                        alert("请先登录！")
                    } else if (data === '0') {
                        alert("该模块已存在！")
                    } else {
                        alert('创建成功！请耐心等待管理员审核');
                        window.history.go(-1);
                    }
                }
            })
        })
    })
</script>

templates/form/postform.html
<form>{% csrf_token %}
    <div class="form-group form-style">
        <label for="headline">标题</label>
        <input type="text" class="form-control" id="headline" name="headline" placeholder="请输入您创建的板块名"/>
    </div>
    <div class="form-group form-style">
        <label for=""></label>
    </div>
    <div class="form-group form-style">
        <label for="description">内容</label>
        <textarea class="form-control" id="description" name="description" rows="8"></textarea>
    </div>
    <div class="form-group form-style">
        <input type="button" id="submit" value="发帖" class="btn btn-primary col-sm-12">
    </div>
</form>

templates/form/signupform.html
<form action="{% url 'app:register' %}" method="post" onsubmit="return submitCheck()">{% csrf_token %}
    <div class="form-group ">
        <label for="email">邮箱</label><span id="emailV" class="col-sm-offset-2 text-center"></span>
        <input type="text" class="form-control" id="email" name="email" placeholder="请输入邮箱"/>
    </div>
    <div class="form-group ">
        <label for="password">密码</label><span id="passwordV" class="col-sm-offset-2 text-center"></span>
        <input type="password" class="form-control" id="password" name="password" placeholder="请输入密码"/>
    </div>
    <div class="form-group ">
        <label for="repeat">确认密码</label><span id="repeatV" class="col-sm-offset-2 text-center"></span>
        <input type="password" class="form-control" id="repeat" placeholder="请再次输入密码"/>
    </div>
    <div class="form-group ">
        <label for="nickname">昵称</label><span id="nicknameV" class="col-sm-offset-2 text-center"></span>
        <input type="text" class="form-control" id="nickname" name="nickname" placeholder="请输入昵称"/>
    </div>
    <div class="form-group ">
        <input type="submit" value="注册" id="submit" class="btn btn-primary col-sm-10 col-sm-offset-1">
    </div>
    <div class="form-group form-style">
        <a href="{% url 'app:login' %}" class="btn btn-link col-sm-12">已有账户？登录</a>
    </div>
</form>

templates/form/tagform.html
<form action="" method="post" onsubmit="">{% csrf_token %}
    <div class="form-group form-style">
        <label for="plate_name">标签名</label>
        <input type="text" class="form-control" id="plate_name" name="plate_name" placeholder="请输入您创建的标签名"/>
    </div>
    <div class="form-group form-style">
        <label for="description">描述你创建的标签</label>
        <textarea class="form-control" id="description" name="description" rows="8"></textarea>
    </div>
    <div class="form-group form-style">
        <input type="button" id="submit" value="提交" class="btn btn-block col-sm-12">
    </div>
</form>
<script>
    $(document).ready(function () {
        $('#submit').click(function () {
            $.ajaxSetup({
                data: {csrfmiddlewaretoken: '{{ csrf_token }}'},
            });

            $.ajax({
                url: "{% url 'app:add_tag' %}",
                data: {
                    "plate_name": $("#plate_name").val(),
                    'description': $("#description").val(),
                },
                type: "POST",
                success: function (data) {
                    if (data === '-1') {
                        alert("请先登录！")
                    } else if (data === '0') {
                        alert("该标签已存在！")
                    } else if (data === '-2') {
                        alert("标签名不能为空！")
                    } else {
                        alert('创建成功！');
                        window.history.go(-1);
                    }
                }
            })
        })
    })
</script>
</html>

templates/form/userchangeform.html
<form id="user_information">{% csrf_token %}
    <div class="col-sm-5">
        <div class="form-group ">
            <label for="nickname">昵称</label><span id="nicknameV" class="col-sm-offset-2 text-center"></span>
            <input type="text" class="form-control" id="nickname" name="nickname" value="{{ user.nickname }}"
                   placeholder="请输入昵称"/>
        </div>
        <div class="form-group ">
            <label for="email">邮箱</label><span id="emailV" class="col-sm-offset-2 text-center"></span>
            <input type="text" class="form-control" id="email" name="email" value="{{ user.email }}"
                   placeholder="请输入邮箱"/>
        </div>
        <div class="form-group">
            <label for="image">头像</label>
            <input type="file" id="avatar" name="avatar" onchange="preview(this)"
                   accept="image/jpeg, image/jpg, image/png,image/PNG">
            <span>请传输正方形的图片</span>
            <div id="preview">
                {% if user.avatar %}
                    <img src="{{ MEDIA_URL }}{{ user.avatar }}" id="current_avatar">
                {% else %}
                    <img src="/static/images/user/user_404.png" id="current_avatar">
                {% endif %}
            </div>
        </div>
    </div>
    <div class="col-sm-5 col-sm-offset-2">
        <div class="form-group ">
            <label for="gender">性别</label>
            <input type="radio" name="gender" value="True">男
            <input type="radio" name="gender" value="False">女
        </div>
        <div class="form-group form-style">
            <label for="description">个人说明</label>
            <textarea class="form-control" id="description" name="description"
                      rows="20">{{ user.description }}</textarea>
        </div>
    </div>


    <div class="form-group form-style">
        <input type="button" id="submit" value="提交" class="btn btn-block col-sm-12">
    </div>
</form>

<script>
    function preview(file) {
        let prevDiv = document.getElementById('preview');
        if (file.files && file.files[0]) {
            let reader = new FileReader();
            reader.onload = function (evt) {
                prevDiv.innerHTML = '<img' + ' style=' + '"width: 200px;height: 200px"' + ' src="' + evt.target.result + '" />';
            }
            reader.readAsDataURL(file.files[0]);
        } else {
            prevDiv.innerHTML = '<div class="img" style="filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(sizingMethod=scale,src=\'' + file.value + '\'"></div>';
        }
    }

    $(document).ready(function () {
        {% if user.gender %}
            $(":radio").get(0).checked = true
        {% else %}
            $(":radio").get(1).checked = true
        {% endif %}

        $("#submit").click(function () {
            $.ajaxSetup({
                data: {csrfmiddlewaretoken: '{{ csrf_token }}'},
            });
            let form = new FormData($("#user_information")[0]);
            $.ajax({
                url: "{% url 'app:modify' %}",
                data: form,
                type: "POST",
                processData: false,
                contentType: false,
                success: function (data) {
                    if (data === '-1') {
                        alert("用户名或者密码错误！")
                    } else if (data === '1') {
                        alert("修改成功")
                        window.location.href = "{% url 'app:showuser' %}?show={{ user.pk }}"
                    } else {
                        alert('修改成功')
                    }
                },
                error: function () {
                    alert('error')
                }
            })
        })
    })
</script>
</html>