api/urls.py
from django.urls import path, include
from api.views import postview, rankview, recommended, replay
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register(r'posts', postview.PostSet)
router.register(r'ranks', rankview.RankSet)
router.register(r'recommended', recommended.RecommendedSet)
router.register(r'ReviewPosts', postview.PostSetOrderForReview)

router.register(r'reply', replay.ReplySet)

app_name = 'api'
urlpatterns = [
    path('', include(router.urls)),
]

app/urls.py
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    # 首页
    path('', views.index, name='index'),
    # 登陆界面
    path('login/', views.login, name='login'),
    # 注册界面
    path('signup/', views.signup, name='signup'),
    # 注册用户
    path('register/', views.register, name='register'),
    # 注销
    path('logout/', views.logout, name='logout'),
    # 进入修改个人资料界面
    path('change/', views.to_change, name='change'),
    # 修改个人资料
    path('modify/', views.modify, name='modify'),
    # 进入发帖界面
    path('posting/', views.posting, name='posting'),
    # 用户展示
    path('showuser/',views.show_user, name='showuser'),
    # 创建板块
    path('create_plate/', views.create_plate, name='create_plate'),
    # 添加板块
    path('add_plate/', views.add_plate, name='add_plate'),
    # 创建标签
    path('create_tag/', views.create_tag, name='create_tag'),
    # 添加标签
    path('add_tag/', views.add_tag, name='add_tag'),
    # 添加帖子
    path('add_post/', views.add_post, name='add_post'),
    # 帖子展示
    path('show_post/', views.post, name='show_post'),
    # 添加点赞
    path('add_like/', views.add_like, name='add_like'),
    # 取消点赞
    path('reduce_like/', views.reduce_like, name='reduce_like'),
    # 添加评论
    path('add_review/', views.add_review, name='add_review'),
    # 展示帖子列表
    path('show_posts/', views.show_posts, name='show_posts'),
    # 动态登录
    path('dynamic_login/', views.dynamic_login, name='dynamic_login'),
    # 获取用户
    path('getuser/', views.get_user, name="get_user"),
    # 发送邮件
    path('sendmail/', views.sendmail, name="sendmail"),
    # 查询
    path('search/', views.search, name='search'),
    # 上传图片
    path('upload_image/', views.upload_image, name="uploadimage"),
    # 最新
    path('latest/', views.latest, name='latest'),
    # 添加回复
    path('addreply/', views.add_replay, name='addreplay'),
    # 修改密码
    path('changepassword/', views.change_password, name='changepassword'),
]

bbs/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve

import xadmin
from bbs.settings import MEDIA_ROOT, DEBUG


urlpatterns = [
    path('admin/', admin.site.urls),
    path('xadmin/', xadmin.site.urls),
    path('api/', include('api.urls')),
    path('', include('app.urls')),

    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT}),

]

#
if not DEBUG:
    from bbs.settings import STATIC_ROOT
    urlpatterns.append(re_path(r'^static/(?P<path>.*)$', serve, {'document_root': STATIC_ROOT}))

user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout, name='logout'),
    path('change/', views.to_change, name='change'),
    path('modify/', views.modify, name='modify'),
    path('posting/', views.posting, name='posting'),
    path('showuser/',views.show_user, name='showuser'),
    path('create_plate/', views.create_plate, name='create_plate'),
    path('add_plate/', views.add_plate, name='add_plate'),
    path('create_tag/', views.create_tag, name='create_tag'),
    path('add_tag/', views.add_tag, name='add_tag'),
    path('add_post/', views.add_post, name='add_post'),
    path('show_post/', views.post, name='show_post'),
    path('add_like/', views.add_like, name='add_like'),
    path('reduce_like/', views.reduce_like, name='reduce_like'),
    path('add_review/', views.add_review, name='add_review'),
    path('show_posts/', views.show_posts, name='show_posts'),
    path('dynamic_login/', views.dynamic_login, name='dynamic_login'),
    path('getuser/', views.get_user, name="get_user"),
    path('sendmail/', views.sendmail, name="sendmail")
]

templates/index.html
{% extends 'base/base.html' %}

{% block title %}首页{% endblock %}
{% block style %}
    <link rel="stylesheet" href="/static/css/swiper.min.css">
    <link rel="stylesheet" href="/static/css/index.css">
{% endblock %}
{% block body %}
    <div class="container-fluid">
        <div class="col-sm-6 col-sm-offset-3">
            <div class="plate-list">
                <ul class="list-group">
                    <li class="active text-center">
                        <a href="{% url 'app:index' %}">
                            <h4>推荐</h4>
                        </a>
                    </li>
                    <li class="text-center plate-item">
                        <a href="{% url 'app:latest' %}">
                            <h4>最新</h4>
                        </a>
                    </li>
                    {% for plate in plates %}
                        {% if forloop.counter <= 17 %}
                            <li class="text-center plate-item">
                                <a href="{% url 'app:show_posts' %}?plate={{ plate.pk }}">
                                    <h4>{{ plate.name }}</h4>
                                </a>
                            </li>
                        {% else %}
                            <li class="hidden hidden-plate text-center plate-item">
                                <a href="{% url 'app:show_posts' %}?plate={{ plate.pk }}">
                                    <h4>{{ plate.name }}</h4>
                                </a>
                            </li>
                        {% endif %}

                    {% endfor %}
                    {% if plates.count > 17 %}
                        <li id="show_more" class="text-center plate-item">
                            <h4>显示更多板块</h4>
                        </li>
                    {% endif %}
                    <li class="text-center plate-item">
                        <a href="{% url 'app:create_plate' %}">
                            <h4>创建板块</h4>
                        </a>
                    </li>
                </ul>
            </div>
            <div class="">
                <div class="swiper-container" id="recommended">
                    <div class="swiper-wrapper" id="wrapper"></div>
                    <div class="swiper-pagination"></div>
                    <div class="swiper-button-prev"></div>
                    <div class="swiper-button-next"></div>
                </div>

                <div class="post-list" id="post-list"></div>
            </div>
        </div>
        <div class="col-sm-2">
            <div class="newest">
                <h5 class="newest-title">最新文章</h5>
                <ul id="newest"></ul>
            </div>
            <div class="newest">
                <h5 class="newest-title">最新评论</h5>
                <ul id="newest-review"></ul>
            </div>
        </div>
        <div id="roof" class="text-center">
            <a href="#"><img src="/static/images/turntoroof.png" style="width: 80px; height: 80px"></a></br>
            返回顶部
        </div>
    </div>

{% endblock %}
{% block script %}
    <script src="/static/js/swiper.min.js"></script>
    <script>

        $(document).ready(function () {

            $.get('/api/recommended?format=json', function (data, status) {
                let results = data.results;
                for (let i = 0; i < results.length; i++) {
                    let id = results[i]['id'];
                    let post;
                    $.get(results[i]['post'], function (data) {
                        post = data
                        let headline = post.headline;
                        let div = document.createElement("div");
                        let h1 = document.createElement("h1");
                        div.setAttribute("class", "swiper-slide");
                        div.style.backgroundImage = "url('" + results[i]['cover'] + "')";
                        div.appendChild(h1);
                        h1.setAttribute('class', "text-center");
                        h1.innerHTML = headline
                        div.addEventListener('click', function () {
                            window.open("{%  url 'app:show_post' %}?post_id=" + post['id'])
                        });

                        document.getElementById("wrapper").appendChild(div);

                        let myswiper = new Swiper('#recommended', {
                            loop: true,
                            grabCursor: true,
                            autoplay: {
                                disableOnInteraction: false,
                            },
                            pagination: {
                                el: '.swiper-pagination',
                                clickable: true,
                                renderBullet: function (index, className) {
                                    return '<span class="' + className + '">' + (index + 1) + '</span>';
                                },
                            },
                            navigation: {
                                nextEl: '.swiper-button-next',
                                prevEl: '.swiper-button-prev',
                            },

                        });

                    });

                }


            }, dataType = "json")
            $.get('/api/posts?format=json&limit=8', function (data, status) {
                let posts = data.results
                for (let i = 0; i < posts.length; i++) {
                    let id = posts[i]['id'];
                    let headline = posts[i]['headline'];
                    let li = document.createElement("li")
                    let a = document.createElement("a");
                    a.innerHTML = headline;
                    a.setAttribute('href', '{% url "app:show_post" %}?post_id=' + id);
                    li.appendChild(a)
                    document.getElementById("newest").appendChild(li)
                }

            }, dataType = "json")
            $.get('/api/ReviewPosts/?limit=8', function (data, status) {
                let posts = data.results
                for (let i = 0; i < posts.length; i++) {
                    let id = posts[i]['id'];
                    let headline = posts[i]['headline'];
                    let li = document.createElement("li")
                    let a = document.createElement("a");
                    a.innerHTML = headline;
                    a.setAttribute('href', '{% url "app:show_post" %}?post_id=' + id);
                    li.appendChild(a)
                    document.getElementById("newest-review").appendChild(li)
                }

            }, dataType = "json")



            $("#show_more").click(function () {
                $(this).remove();
                $(".hidden-plate").removeClass("hidden")
            })
            $('.plate-description-detail').hover(function () {
                $(this).popover('show')
            }, function () {
                $(this).popover('hide')
            })
            $(".post-item").hover(function () {
                $(this).addClass("post-hover")
            }, function () {
                $(this).removeClass("post-hover")
            })
            $(".plate-item").hover(function () {
                $(this).addClass("active")
            }, function () {
                $(this).removeClass("active")
            })
            let offset = 0;
            document.getElementById("post-list").innerHTML += "<div class='text-center post-item' id='loading'><h3>加载中，请稍后......</h3></div>";
            loadpost(offset)
            $(window).scroll(function () {
                var scrollTop = $(this).scrollTop();
                var scrollHeight = $(document).height();
                var windowHeight = $(this).height();
                if (scrollTop + windowHeight == scrollHeight) {
                    offset += 30;
                    document.getElementById("post-list").innerHTML += "<div class='text-center post-item' id='loading'><h3>加载中，请稍后......</h3></div>";
                    loadpost(offset)
                }
            });
        })
        function loadpost(offset) {

            $.get('/api/ranks/?format=json&offset='+offset, function (data) {
                let ranks = data.results;
                if (document.getElementById('loading')){
                    document.getElementById('loading').remove();
                }
                for (let i = 0; i < ranks.length; i++) {
                    $.get(ranks[i]['post'], function (data) {
                        let post = data;
                        let html = '<div class="post-item">\n' +
                            '                            <a class="post-title" href="' + "{% url 'app:show_post' %}?post_id=" + post['id'] + '">\n' +
                            '                                <h4>' + post['headline'] + '</h4></a>\n' +
                            '                            <div class="description">' + post['description'].replace(/<[^>]+>/g, "") + '</div>\n' +
                            '                            <div class="container-fluid">\n' +
                            '                                <div class="row">\n' +
                            '                                    <div class="col-sm-9">\n' +
                            '                                        <a href="{% url 'app:showuser' %}?show=' + post['user']['id'] + '">\n' +
                            '                                                <img src="' + avatar_src(post['user']['avatar']) + '" class="user_avatar">\n' +
                            '                                        | <a\n' +
                            '                                            href="{% url 'app:show_posts' %}?plate=' + post['plate']['id'] + '">' + post['plate']['name'] + '</a>\n' +
                            '                                        | ' + post['create_time'].split('+')[0].replace("T", " ") + '\n' +
                            '                                    </div>\n' +
                            '                                    <div class="col-sm-3 text-right">\n' +
                            '                                        阅读' + post['read_num'] + ' | 评论数 ' + post['reviews'].length + '\n' +
                            '                                    </div>\n' +
                            '                                </div>\n' +
                            '                            </div>\n' +
                            '                        </div>'
                        document.getElementById("post-list").innerHTML += html
                    })
                }
            });

        }
        function create_element(tag) {
            return document.createElement(tag)
        }

        function addClass(element, classname) {
            return null
        }


        function avatar_src(url) {
            if (url == null) {
                return "/static/images/user/user_404_title.png"
            } else {
                return url
            }
        }
    </script>
{% endblock %}

templates/index1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>论坛</title>
    <link rel="stylesheet" type="text/css" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="/static/css/base.css">
    <script type="text/javascript" src="/static/js/jquery-3.3.1.min.js"></script>
    <script type="text/javascript" src="/static/js/bootstrap.min.js"></script>
    <style>
        .plate-list {
            background-color: white;
        }

        .list-group {
            min-height: 500px;
        }
    </style>
</head>
<body>
{% include 'base/navigate.html' %}
<div class="body">
    <div class="container-fluid">
        <div class="col-sm-2 col-sm-offset-2 plate-list">
            <div class="list-group">
                {% for plate in plates %}

                    <a class="list-group-item" href="{% url 'user:show_posts' %}?plate={{ plate.pk }}">
                        <h4 class="list-group-item-heading">
                            {{ plate.name }}
                        </h4>
                        <div class="list-group-item-text text-right">
                            <p class="btn btn-link plate-description-detail" role="button" data-container="body"
                               data-toggle="popover"
                               data-placement="right" data-content="{{ plate.description }}"
                               title="{{ plate.name }}">详情></p>
                        </div>

                    </a>

                {% endfor %}
                {% if hottest.count == 8 %}
                    <a href="" class="list-group-item" >显示更多板块
                    </a>
                {% endif %}
                <a class="list-group-item" href="{% url 'user:create_plate' %}">创建板块</a>
            </div>
        </div>
        <div class="col-sm-5">
            <div class="">
                <ul class="nav nav-tabs">
                    <li role="presentation" class="active"><a>最热榜</a></li>
                </ul>
                <div class="list-group">
                    {% for post in hottest %}
                        <a class="list-group-item" href="{% url 'user:show_post' %}?post_id={{ post.pk }}">
                            <div class="list-group-item-heading">{{ post.headline }}
                                <span class="label label-info">{{ post.plate.name }}</span>
                                <div class="text-right">{{ post.user.nickname }}</div>

                            </div>
                            <p class="text-right">
                                {% for tag in post.tags.all %}
                                    <span class="label label-default">{{ tag.name }}</span>
                                {% endfor %}
                                {{ post.last_change_time }}
                            </p>
                        </a>
                    {% endfor %}
                </div>
            </div>
            <div class="">
                <ul class="nav nav-tabs">
                    <li role="presentation" class="active"><a>最新榜</a></li>
                </ul>
                <div class="list-group">
                    {% for post in latest %}
                        <a class="list-group-item" href="{% url 'user:show_post' %}?post_id={{ post.pk }}">
                            <div class="list-group-item-heading">{{ post.headline }}
                                <span class="label label-info">{{ post.plate.name }}</span>
                                <div class="text-right">{{ post.user.nickname }}</div>

                            </div>
                            <p class="text-right">
                                {% for tag in post.tags.all %}
                                    <span class="label label-default">{{ tag.name }}</span>
                                {% endfor %}
                                {{ post.last_change_time }}
                            </p>
                        </a>
                    {% endfor %}
                </div>
                <table class="table">
                    <tbody>


                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% include 'base/suggestion.html' %}
</body>
<script type="text/javascript">

    $(document).ready(function () {
        $('.plate-description-detail').hover(function () {
            $(this).popover('show')
        }, function () {
            $(this).popover('hide')
        })
    })
</script>
</html>

templates/latest.html
{% extends 'base/base.html' %}

{% block title %}最新{% endblock %}
{% block style %}
    <style>
        .post-list {
            background-color: white;
            margin-left: 3%;
        }

        .post-item {
            padding: 5px 1.5% 0;
            border: rgb(245, 246, 247) solid 1px;
            border-radius: 3px;
        }

        .post-hover {
            background-color: #fafafa;
        }


        .description {
            color: #8a8a8a;
            white-space: nowrap;
            text-overflow: ellipsis;
            text-overflow: ellipsis;
            overflow: hidden;
        }


        .post-title {
            color: black;
        }

        .newest {
            background-color: white;
        }

        .newest-title {
            padding: 20px;
            margin: 10px 0;
            border: 1px solid #eee;
            border-left-width: 5px;
            border-left-color: #ce4044;
            border-radius: 3px;
        }

        #roof {
            position: fixed;
            bottom: 10%;
            right: 10%;
        }
    </style>
{% endblock %}
{% block body %}
    <div class="container-fluid" id="newest-recommended">
        <div class="col-sm-6 col-sm-offset-3">
            <div class="plate-list">
                <ul class="list-group">
                    <li class="text-center plate-item">
                        <a href="{% url 'app:index' %}">
                            <h4>推荐</h4>
                        </a>
                    </li>
                    <li class="active text-center">
                        <a href="{% url 'app:latest' %}">
                            <h4>最新</h4>
                        </a>
                    </li>
                    {% for plate in plates %}
                        <li class="text-center plate-item">
                            <a href="{% url 'app:show_posts' %}?plate={{ plate.pk }}">
                                <h4>{{ plate.name }}</h4>
                            </a>
                        </li>
                    {% endfor %}
                    {% if plates.count > 5 %}
                        <li id="show_more" class="text-center plate-item">
                            <h4>显示更多板块</h4>
                        </li>
                    {% endif %}
                    <li class="text-center plate-item">
                        <a href="{% url 'app:create_plate' %}">
                            <h4>创建板块</h4>
                        </a>
                    </li>
                </ul>
            </div>
            <div class="">
                <div class="post-list" id="post-list">

                </div>
            </div>
        </div>
        <div class="col-sm-2">
            <div class="newest">
                <h5 class="newest-title">热门推荐</h5>
                <ul id="newest"></ul>
            </div>
            <div class="newest">
                <h5 class="newest-title">最新评论</h5>
                <ul id="newest-review"></ul>
            </div>
        </div>
        <div id="roof" class="text-center">
            <a href="#"><img src="/static/images/turntoroof.png" style="width: 80px; height: 80px"></a></br>
            返回顶部
        </div>
    </div>

{% endblock %}
{% block script %}
    <script>

        $(document).ready(function () {
            let offset = 0;
            $("#show_more").click(function () {
                $(this).remove();
                $(".hidden-plate").removeClass("hidden")
            })
            $('.plate-description-detail').hover(function () {
                $(this).popover('show')
            }, function () {
                $(this).popover('hide')
            })
            $(".post-item").hover(function () {
                $(this).addClass("post-hover")
            }, function () {
                $(this).removeClass("post-hover")
            })
            $(".plate-item").hover(function () {
                $(this).addClass("active")
            }, function () {
                $(this).removeClass("active")
            });
            document.getElementById("post-list").innerHTML += "<div class='text-center post-item' id='loading'><h3>加载中，请稍后。。。。</h3></div>"
            loadpost(offset);
            $.get('/api/ranks?format=json&limit=8', function (data, status) {
                let posts = data.results;

                for (let i = 0; i < posts.length; i++) {
                    $.get(posts[i]['post'], function (data) {
                        let id = data['id'];
                        let headline = data['headline'];
                        let li = document.createElement("li")
                        let a = document.createElement("a");
                        a.innerHTML = headline;
                        a.setAttribute('href', '{% url "app:show_post" %}?post_id=' + id);
                        li.appendChild(a)
                        document.getElementById("newest").appendChild(li)
                    });

                }

            }, dataType = "json")
            $.get('/api/ReviewPosts/?limit=8', function (data, status) {
                let posts = data.results
                for (let i = 0; i < posts.length; i++) {
                    let id = posts[i]['id'];
                    let headline = posts[i]['headline'];
                    let li = document.createElement("li")
                    let a = document.createElement("a");
                    a.innerHTML = headline;
                    a.setAttribute('href', '{% url "app:show_post" %}?post_id=' + id);
                    li.appendChild(a)
                    document.getElementById("newest-review").appendChild(li)
                }

            }, dataType = "json")
            $(window).scroll(function () {
                var scrollTop = $(this).scrollTop();
                var scrollHeight = $(document).height();
                var windowHeight = $(this).height();
                if (scrollTop + windowHeight == scrollHeight) {
                    offset += 30;
                    document.getElementById("post-list").innerHTML += "<div class='text-center post-item' id='loading'><h3>加载中，请稍后......</h3></div>"
                    loadpost(offset)
                }
            });
        });

        function loadpost(offset) {


            $.get('/api/posts/?format=json&offset=' + offset, function (data) {

                let ranks = data.results;
                document.getElementById('loading').remove();
                for (let i = 0; i < ranks.length; i++) {

                    let post = ranks[i];
                    let html = '<div class="post-item">\n' +
                        '                            <a class="post-title" href="' + "{% url 'app:show_post' %}?post_id=" + post['id'] + '">\n' +
                        '                                <h4>' + post['headline'] + '</h4></a>\n' +
                        '                            <div class="description">' + post['description'].replace(/<[^>]+>/g, "") + '</div>\n' +
                        '                            <div class="container-fluid">\n' +
                        '                                <div class="row">\n' +
                        '                                    <div class="col-sm-9">\n' +
                        '                                        <a href="{% url 'app:showuser' %}?show=' + post['user']['id'] + '">\n' +
                        '                                                <img src="' + avatar_src(post['user']['avatar']) + '" class="user_avatar">\n' +
                        '                                        | <a\n' +
                        '                                            href="{% url 'app:show_posts' %}?plate=' + post['plate']['id'] + '">' + post['plate']['name'] + '</a>\n' +
                        '                                        | ' + post['create_time'].split('+')[0].replace("T", " ") + '\n' +
                        '                                    </div>\n' +
                        '                                    <div class="col-sm-3 text-right">\n' +
                        '                                        阅读' + post['read_num'] + ' | 评论数 ' + post['reviews'].length + '\n' +
                        '                                    </div>\n' +
                        '                                </div>\n' +
                        '                            </div>\n' +
                        '                        </div>'
                    document.getElementById("post-list").innerHTML += html

                }
            });
        }

        function avatar_src(url) {
            if (url == null) {
                return "/static/images/user/user_404_title.png"
            } else {
                return url
            }
        }
    </script>
{% endblock %}