api/urls.py
from django.urls import path, include
from api.views import postview, rankview, recommended, replay
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register(r'posts', postview.PostSet)
router.register(r'ranks', rankview.RankSet)
router.register(r'recommended', recommended.RecommendedSet)
router.register(r'ReviewPosts', postview.PostSetOrderForReview)

router.register(r'reply', replay.ReplySet)

app_name = 'api'
urlpatterns = [
    path('', include(router.urls)),
]

app/urls.py
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    # 首页
    path('', views.index, name='index'),
    # 登陆界面
    path('login/', views.login, name='login'),
    # 注册界面
    path('signup/', views.signup, name='signup'),
    # 注册用户
    path('register/', views.register, name='register'),
    # 注销
    path('logout/', views.logout, name='logout'),
    # 进入修改个人资料界面
    path('change/', views.to_change, name='change'),
    # 修改个人资料
    path('modify/', views.modify, name='modify'),
    # 进入发帖界面
    path('posting/', views.posting, name='posting'),
    # 用户展示
    path('showuser/',views.show_user, name='showuser'),
    # 创建板块
    path('create_plate/', views.create_plate, name='create_plate'),
    # 添加板块
    path('add_plate/', views.add_plate, name='add_plate'),
    # 创建标签
    path('create_tag/', views.create_tag, name='create_tag'),
    # 添加标签
    path('add_tag/', views.add_tag, name='add_tag'),
    # 添加帖子
    path('add_post/', views.add_post, name='add_post'),
    # 帖子展示
    path('show_post/', views.post, name='show_post'),
    # 添加点赞
    path('add_like/', views.add_like, name='add_like'),
    # 取消点赞
    path('reduce_like/', views.reduce_like, name='reduce_like'),
    # 添加评论
    path('add_review/', views.add_review, name='add_review'),
    # 展示帖子列表
    path('show_posts/', views.show_posts, name='show_posts'),
    # 动态登录
    path('dynamic_login/', views.dynamic_login, name='dynamic_login'),
    # 获取用户
    path('getuser/', views.get_user, name="get_user"),
    # 发送邮件
    path('sendmail/', views.sendmail, name="sendmail"),
    # 查询
    path('search/', views.search, name='search'),
    # 上传图片
    path('upload_image/', views.upload_image, name="uploadimage"),
    # 最新
    path('latest/', views.latest, name='latest'),
    # 添加回复
    path('addreply/', views.add_replay, name='addreplay'),
    # 修改密码
    path('changepassword/', views.change_password, name='changepassword'),
]

bbs/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve

import xadmin
from bbs.settings import MEDIA_ROOT, DEBUG


urlpatterns = [
    path('admin/', admin.site.urls),
    path('xadmin/', xadmin.site.urls),
    path('api/', include('api.urls')),
    path('', include('app.urls')),

    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT}),

]

#
if not DEBUG:
    from bbs.settings import STATIC_ROOT
    urlpatterns.append(re_path(r'^static/(?P<path>.*)$', serve, {'document_root': STATIC_ROOT}))

user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout, name='logout'),
    path('change/', views.to_change, name='change'),
    path('modify/', views.modify, name='modify'),
    path('posting/', views.posting, name='posting'),
    path('showuser/',views.show_user, name='showuser'),
    path('create_plate/', views.create_plate, name='create_plate'),
    path('add_plate/', views.add_plate, name='add_plate'),
    path('create_tag/', views.create_tag, name='create_tag'),
    path('add_tag/', views.add_tag, name='add_tag'),
    path('add_post/', views.add_post, name='add_post'),
    path('show_post/', views.post, name='show_post'),
    path('add_like/', views.add_like, name='add_like'),
    path('reduce_like/', views.reduce_like, name='reduce_like'),
    path('add_review/', views.add_review, name='add_review'),
    path('show_posts/', views.show_posts, name='show_posts'),
    path('dynamic_login/', views.dynamic_login, name='dynamic_login'),
    path('getuser/', views.get_user, name="get_user"),
    path('sendmail/', views.sendmail, name="sendmail")
]

user/models.py
from django.db import models


# Create your models here.
# 用户
def avatar(self, filename):
    return 'user/' + str(self.pk) + '/avatar/init.'+filename.split('.')[-1]


class User(models.Model):
    password = models.CharField(max_length=40)
    email = models.EmailField(unique=True)
    gender = models.BooleanField(default=True)
    nickname = models.CharField(max_length=20, unique=True)
    avatar = models.ImageField(upload_to=avatar, default=None, null=True)
    description = models.TextField(null=True, default=None)


# 板块
class Plate(models.Model):
    name = models.CharField(max_length=10, unique=True, null=False)
    create_user = models.ForeignKey(User, to_field='nickname', on_delete=models.DO_NOTHING)
    description = models.TextField(null=True, default=True)
    audit = models.BooleanField(default=False)
    create_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


# 标签
class Tag(models.Model):
    name = models.CharField(max_length=10, unique=True, null=False)
    create_user = models.ForeignKey(User, to_field='nickname', on_delete=models.DO_NOTHING)
    description = models.TextField(null=True, default=None)

    def __str__(self):
        return self.name


# 帖子
class Post(models.Model):
    user = models.ForeignKey(User, to_field='nickname', on_delete=models.DO_NOTHING)
    headline = models.CharField(max_length=20)
    plate = models.ForeignKey(Plate, to_field='name', on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag)
    create_time = models.DateTimeField(auto_now_add=True)
    last_change_time = models.DateTimeField(auto_now=True)
    description = models.TextField(null=True, default=None)
    give_a_like = models.IntegerField(default=0)
    text_choice = models.BooleanField(null=True)

    def __str__(self):
        return self.headline


# 评论
class Review(models.Model):
    review = models.TextField()
    time = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING)

    def __str__(self):
        return self.review


# 点赞
class GiveLike(models.Model):
    post = models.ForeignKey(Post, on_delete=models.DO_NOTHING)
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING)

user/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse

from user.util import plateutil, tagutil, postutil, reviewutil, pageutil, randomutil, mailutil
from .models import User, Plate, Tag, Post, Review
from .util import userutil, requestutil


# Create your views here.


def login(request):
    request.session.clear()
    email = request.POST.get('email')
    password = request.POST.get('password')
    message = ''
    if email:
        user = userutil.login(email=email, password=password)
        if user:
            request.session['user'] = user.pk
            request.session.set_expiry(0)
            return index(request)
        else:
            message = '用户名不存在或者密码错误'

    context = {
        'message': message,
    }
    return render(request, 'user/login.html', context=context)


def dynamic_login(request):
    try:
        del request.session["user"]
    except:
        pass
    email = request.POST.get('email')
    captcha = request.POST.get('captcha')
    message = ''
    try:
        if email == request.session.get("email") and captcha == request.session.get("captcha"):
            user = userutil.get_user_for_email(email)
            request.session['user'] = user.pk
            request.session.set_expiry(0)
            return index(request)
        else:
            message = '用户名不存在或者验证码错误'
    except Exception as e :
        pass

    context = {
        'message': message,
    }
    return render(request, 'user/dynamiclogin.html', context=context)


def get_user(request):
    email = request.GET.get('email')
    if userutil.get_user_for_email(email):
        return HttpResponse(1)
    else:
        return HttpResponse(0)


def sendmail(request):
    email = request.GET.get('email')
    if userutil.get_user_for_email(email):
        captcha = randomutil.generate(4)
        if mailutil.senderEmail(captcha, email):
            request.session['email'] = email
            request.session['captcha'] = captcha
            return HttpResponse(1)
        else:
            return HttpResponse(0)
    else:
        return HttpResponse(0)


def signup(request):
    request.session.clear()
    return render(request, 'user/signup.html')


def register(request):
    context = {
        'result': False,
    }
    if userutil.add_user(email=request.POST.get('email'), password=request.POST.get('password'),
                         nickname=request.POST.get('nickname')):
        context['result'] = True

    return render(request, 'user/result.html', context=context)


def index(request):
    pk = requestutil.get_session(name='user', request=request)
    context = {
        'user': userutil.get_user(user_id=pk),
        'plates': Plate.objects.filter(audit=True),
        'latest': Post.objects.all().order_by('-create_time')[0:5],
        'hottest': Post.objects.all().order_by('-give_a_like')[0:5],
    }
    return render(request, 'index.html', context=context)


def logout(request):
    request.session.clear()
    return HttpResponseRedirect('/')


def create_plate(request):
    user_id = requestutil.get_session(name='user', request=request)
    user = userutil.get_user(user_id)
    context = {
        'user': user,
        'form': 'plate',
    }
    return render(request, 'plate/create.html', context=context)


def add_plate(request):
    description = request.POST.get('description')
    plate_name = request.POST.get('plate_name')
    id = requestutil.get_session(name='user', request=request)
    message = plateutil.add_plate(name=plate_name, description=description, user_id=id)
    return HttpResponse(message)


def create_tag(request):
    user_id = requestutil.get_session(name='user', request=request)
    user = userutil.get_user(user_id)
    context = {
        'user': user,
        'form': 'tag',
    }
    return render(request, 'plate/create.html', context=context)


def add_tag(request):
    description = request.POST.get('description')
    tag_name = request.POST.get('plate_name')
    id = requestutil.get_session(name='user', request=request)
    message = tagutil.add_tag(tag_name=tag_name, description=description, user_id=id)
    return HttpResponse(message)


def show_user(request):
    user_id = requestutil.get_session(name='user', request=request)
    show = request.GET.get('show')
    page = 1
    try:
        page = int(request.GET.get('page'))
        if page < 0:
            page = 1
    except:
        pass
    showuser = userutil.get_user(show)
    posts = postutil.get_posts_for_user(showuser)
    current_page = pageutil.get_one_page(posts, page, 5)
    context = {
        'user': userutil.get_user(user_id),
        'showuser': showuser,
        'current_page': current_page,
        'total_post': posts.count(),
    }
    return render(request, 'user/show.html', context=context)


def to_change(request):
    user_id = requestutil.get_session(name='user', request=request)
    user = userutil.get_user(user_id)
    context = {
        'user': user,
    }
    return render(request, 'user/change.html', context=context)


def modify(request):
    user_information = {
        'email': request.POST.get('email'),
        'password': request.POST.get('password'),
        'nickname': request.POST.get('nickname'),
        'avatar': request.FILES.get('avatar'),
        'gender': request.POST.get('gender'),
        'description': request.POST.get('description'),
    }
    message = userutil.modify_information(user_information)
    return HttpResponse(message)


def posting(request):
    user_id = requestutil.get_session(name='user', request=request)
    user = userutil.get_user(user_id)
    context = {
        'user': user,
        'plates': plateutil.get_for_audit(True),
        'tags': Tag.objects.all(),
    }
    return render(request, 'post/create.html', context=context)


def add_post(request):
    user_id = requestutil.get_session(name='user', request=request)
    new_post = {
        'headline': request.POST.get('headline'),
        'plate': request.POST.get('plate'),
        'tag_list': request.POST.get('tag_list'),
        'description': request.POST.get('description'),
        'text_choice': request.POST.get('text_choice'),
    }
    message = postutil.add(user_id=user_id, post=new_post)

    return HttpResponse(message)


def post(request):
    user_pk = requestutil.get_session(name='user', request=request)
    post_id = request.GET.get('post_id')
    post = postutil.get(pk=post_id)
    context = {
        'post': post,
        'user': userutil.get_user(user_id=user_pk),
        'reviews': Review.objects.filter(post=post).order_by('-time'),
        'posts': postutil.get_posts_for_user(post.user, order='-create_time')[0:5],
    }
    return render(request, 'post/show.html', context=context)


def add_like(request):
    post_pk = request.POST.get('post_pk')
    post = Post.objects.get(pk=post_pk)
    post.give_a_like = post.give_a_like + 1
    post.save()
    return HttpResponse(1)


def reduce_like(request):
    post_pk = request.POST.get('post_pk')
    post = Post.objects.get(pk=post_pk)
    post.give_a_like = post.give_a_like - 1
    post.save()
    return HttpResponse(1)


def add_review(request):
    review = request.POST.get('review')
    post_pk = request.POST.get('post_pk')
    user_pk = requestutil.get_session(name='user', request=request)
    respose = reviewutil.add_review(user_pk=user_pk, post_pk=post_pk, content=review)
    return HttpResponse(respose)


def show_posts(request):
    plate_pk = request.GET.get('plate')
    user_pk = requestutil.get_session(name='user', request=request)
    plate = plateutil.get(plate_pk)
    posts = postutil.get_posts_for_plate(plate_pk)
    context = {
        'plate': plate,
        'posts': posts,
        'hottest': posts.order_by('-give_a_like'),
        'latest': posts.order_by('-create_time'),
        'user': userutil.get_user(user_id=user_pk),
    }

    return render(request, 'plate/showpost.html', context=context)


def show_post_for_search(request):
    pass

templates/user/change.html
{% extends 'base/base.html' %}


{% block title %}
    修改个人资料
{% endblock %}


{% block style %}
    <style type="text/css">
        .propagranda {
            margin-top: 50px;
        }
    </style>
{% endblock %}


{% block body %}
    <div class="container-fluid ">
        <div class="row propagranda">
            <div class="col-sm-6 col-sm-offset-3 form">
                {% include 'form/userchangeform.html' %}
            </div>
        </div>
    </div>
{% endblock %}


{% block script %}

{% endblock %}

templates/user/changepassword.html
{% extends 'base/base.html' %}


{% block title %}
    登录
{% endblock %}


{% block style %}

{% endblock %}


{% block body %}
    <div class="container-fluid ">
        <div class="row propagranda">
            <div class="col-sm-6 col-sm-offset-2">
                {% include 'base/advertisement.html' %}
            </div>
            <div class="col-sm-2 form">
                <div class="text-center"><h2>找回密码</h2></div>
                <form id="changepassowrd">{% csrf_token %}
                    <div class="form-group form-style">
                        <label for="email">邮 箱:<span id="email_v"></span></label>

                        <input type="text" class="form-control" id="email" name="email" placeholder="请输入邮箱"/>
                        <span></span>
                    </div>
                    <div class="form-group form-style">
                        <label for="captcha">验证码: <span id="captcha_v"></span></label>
                        <input type="text" class="form-control captcha" id="captcha" name="captcha" maxlength="6"
                               disabled="disabled"/>
                    </div>
                    <div class="form-group form-style">
                        <label for="new">新密码<span id="new_v"></span></label>
                        <input type="password" id="new" class="form-control captcha" name="password"
                               disabled="disabled">
                    </div>
                    <div class="form-group form-style">
                        <label for="repeat">确认密码<span id="repeat_v"></span></label>
                        <input type="password" id="repeat" class="form-control captcha" name="repeat"
                               disabled="disabled">
                    </div>

                    <div class="form-group form-style">
                        <input type="button" value="确认修改" class="btn btn-primary col-sm-12" id="submit">
                    </div>
                </form>

            </div>
        </div>
    </div>
{% endblock %}


{% block script %}
    <script>
        $(document).ready(function () {
            let new_v = false;
            let captcha = false;
            let repeat = false;
            $('#email').blur(function () {

                $.get("{% url 'app:get_user' %}?email=" + $(this).val(), function (data) {
                    let result = 1
                    if (data === '1') {
                        message = "邮箱已注册！<input type=\"button\" class=\"btn btn-default btn-sm sendmail\" id='sendcode' value=\"发送验证码\"/>"

                    } else {
                        message = "邮箱未注册！"
                        result = 0
                    }
                    putresult("email_v", message, result)
                })
            });
            $("#captcha").blur(function () {
                let message = "";
                if ($(this).val().length != 4) {
                    message = "请输入正确的验证码";
                    captcha = false
                }else {
                    captcha = true;
                }
                putresult('captcha_v', message, 0);
            })

            $("body").on("click", "#sendcode", function () {
                $.get("{% url 'app:sendmail' %}?email=" + $("#email").val(), function (data) {
                    if (data === '1') {
                        alert('验证码已发送');
                        $(".captcha").removeAttr("disabled");
                    } else if (data === "0") {
                        alert("发送失败！");
                    }
                })
            });
            $("#new").blur(function () {
                if ($(this).val().length < 6) {
                    putresult('new_v', "密码长度不得小于6", 0);
                    new_v = false
                } else {
                    new_v = true
                }
            });
            $("#repeat").blur(function () {
                if ($(this).val() != $("#new").val()) {
                    putresult('repeat_v', "两次密码不一致", 0);
                    repeat = false
                } else {
                    repeat = true
                }

            });
            $("#submit").click(function () {
                if ( new_v && repeat && captcha) {
                    let formdata = $("#changepassowrd").serializeArray()
                    $.post("{% url 'app:changepassword' %}", formdata, function (data) {
                        alert(data);
                        if (data == "修改成功"){
                            window.location.href = '{% url "app:login" %}'
                        }
                    })
                }

            });
        });

        function putresult(id, message, result = 1) {
            let obj = "#" + id;
            let color = "green"
            $(obj).html(message);
            if (result == 0) {
                color = "red";
            }
            $(obj).css('color', color)
        }
    </script>
{% endblock %}

templates/user/dynamiclogin.html
{% extends 'base/base.html' %}


{% block title %}
    登录
{% endblock %}


{% block style %}

{% endblock %}


{% block body %}
    <div class="container-fluid ">
        <div class="row propagranda">
            <div class="col-sm-6 col-sm-offset-2">
                {% include 'base/advertisement.html' %}
            </div>
            <div class="col-sm-2 form">
                <div class="text-center"><h1>验证码登录</h1></div>
                <form action="{% url 'app:dynamic_login' %}" method="post">{% csrf_token %}
                    <div class="form-group form-style">
                        <label for="email">邮 箱:<span id="email_v"></span></label>

                        <input type="text" class="form-control" id="email" name="email" placeholder="请输入邮箱"/>
                        <span></span>
                    </div>
                    <div class="form-group form-style">
                        <label for="captcha">验证码: <span id="captcha_v"></span></label>
                        <input type="text" class="form-control" id="captcha" name="captcha" maxlength="6" disabled="disabled"/>
                    </div>

                    <div class="form-group form-style">
                        <a href="{% url 'app:login' %}" class="btn btn-link col-sm-12">账户密码登录</a>
                        <input type="submit" value="登录" class="btn btn-primary col-sm-12">
                        <a href="{% url 'app:signup' %}" class="btn btn-link col-sm-12">现在注册</a>
                    </div>
                </form>

            </div>
        </div>
    </div>
{% endblock %}


{% block script %}
    <script>
        $(document).ready(function () {
            $('#email').blur(function () {

                $.get("{% url 'app:get_user' %}?email="+$(this).val(), function(data){
                    let result = 1
                    if(data === '1'){
                        message = "邮箱已注册！<input type=\"button\" class=\"btn btn-default btn-sm sendmail\" id='sendcode' value=\"发送验证码\"/>"

                    }else {
                        message = "邮箱未注册！"
                        result = 0
                    }
                    putresult("email_v", message, result)
                })
            })
            $("#captcha").blur(function () {
                let message = "";
                if($(this).val().length != 4){
                    message = "请输入正确的验证码";
                }
                putresult('captcha_v', message, 0);
            })

            $("body").on("click", "#sendcode",function () {
                $.get("{% url 'app:sendmail' %}?email="+$("#email").val(),function(data){
                    if (data === '1'){
                        alert('验证码已发送');
                        $("#captcha").removeAttr("disabled");
                    } else if (data === "0") {
                        alert("发送失败！");
                    }
                })
            })
        })
    function putresult(id, message, result) {
        let obj = "#"+ id;
        let color = "green"
        $(obj).html(message);
        if (result == 0){
            color = "red";
        }
        $(obj).css('color', color)
    }
    </script>
{% endblock %}

templates/user/result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>结果</title>
</head>
<body>
    <div>
        {% if  result  %}
            <div> 注册成功！请前往<a href="{% url 'app:login' %}">登录</a> </div>
        {% else %}
            <div>注册失败! 请重新<a href="{% url 'app:signup' %}">注册</a></div>
        {% endif %}
            <div>3秒后自动跳转</div>

    </div>
</body>
<script type="text/javascript">
    function run() {
        {% if  result  %}
            top.location = '{% url 'app:login' %}'
        {% else %}
            top.location = '{% url 'app:signup' %}'
        {% endif %}
    }
    window.setTimeout(run, 3000)
</script>
</html>

templates/user/show.html
{% extends 'base/base.html' %}

{% block title %}
    {{ showuser.nickname }}的个人主页
{% endblock %}


{% block style %}
    <style>
        img {
            height: 200px;
            width: 200px;
            border-radius: 50%;
        }

        #username {
            font-size: 30px;
        }

        .list-group {
            min-height: 400px;
        }
    .description {
            color: #8a8a8a;
            white-space: nowrap;
            text-overflow: ellipsis;
            text-overflow: ellipsis;
            overflow: hidden;
        }
    </style>
{% endblock %}


{% block body %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-3 col-sm-offset-2 bg-white">

                <div class="thumbnail center-block">
                    {% if showuser.avatar %}
                        <img src="/media/{{ showuser.avatar }}" alt="">
                    {% else %}
                        <img src="/static/images/user/user_404.png" alt="头像不存在">
                    {% endif %}

                    <div class="caption">
                        <h3>{{ showuser.nickname }}
                            {% if showuser.gender %}
                                <small style="color: #5bc0de">♂</small>
                            {% else %}
                                <small style="color: deeppink">♀</small>
                            {% endif %}
                        </h3>

                        <p> 个人说明：{{ showuser.description }}</p>
                        {% if showuser.pk == user.pk %}
                            <p>
                                <a href="{% url 'app:changepassword' %}">修改密码</a>
                                <a href="{% url 'app:change' %}" class="btn btn-link" role="button">修改个人信息</a>
                            </p>
                        {% endif %}
                    </div>
                </div>

            </div>
            <div class="col-sm-5 bg-white">
                <ul class="nav nav-tabs">
                    <li role="presentation" class="active">
                        <a>
                            {% if showuser == user %}
                                您的发帖
                            {% else %}
                                他的发帖
                            {% endif %}
                        </a>
                    </li>
                </ul>
                <div class="list-group">
                    {% for post in current_page %}
                        <div class="post-item">
                            <a class="post-title" href="{% url 'app:show_post' %}?post_id={{ post.pk }}">
                                <h4>{{ post.headline }}</h4></a>
                            <div class="description">{{ post.description| striptags }}</div>
                            <div class="container-fluid">
                                <div class="row">
                                    <div class="col-sm-9">
                                        <a
                                            href="{% url 'app:show_posts' %}?plate={{ post.plate.pk }}">{{ post.plate.name }}</a>>
                                        | {{ post.create_time | timesince}}以前
                                    </div>
                                    <div class="col-sm-3 text-right">
                                        阅读 {{ post.read_num }} | 评论数 {{ post.reviews.count }}
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}

                </div>

                {% if total_post == 0 and showuser.pk == user.pk %}
                    <div class="alert alert-warning text-center">您还没有<a href="{% url 'app:posting' %}">发帖</a>，</div>
                {% elif total_post == 0 and showuser.pk != user.pk %}
                    <div class="alert alert-warning text-center">这个人还没有发过贴呢，</div>
                {% else %}
                    <div class="text-center">
                        <nav aria-label="Page navigation" class="text-center">
                            <ul class="pagination page-list">
                                <li>
                                    <a id="first-page" href="{% url 'app:showuser' %}?show={{ showuser.pk }}&page=1">
                                        <span aria-hidden="true">首页;</span>
                                    </a>
                                </li>

                                <li>
                                    <a id="previous-page">
                                        <span aria-hidden="true">上一页</span>
                                    </a>
                                </li>

                                <li><a class="page-item-hottest">第{{ current_page.number }}页</a></li>
                                <li>
                                    <a id="next-page">
                                        <span aria-hidden="true">下一页</span>
                                    </a>
                                </li>

                                <li>
                                    <a id="last-page"
                                       href="{% url 'app:showuser' %}?show={{ showuser.pk }}&page={{ current_page.paginator.num_pages }}">
                                        <span aria-hidden="true">尾页</span>
                                    </a>
                                </li>
                            </ul>
                        </nav>

                    </div>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}


{% block script %}
    <script>
        $(document).ready(function () {
            {% if current_page.has_previous %}
                $('#previous-page').attr('href', "{% url 'app:showuser' %}?show={{ showuser.pk }}&page={{ current_page.previous_page_number }}")

            {% endif %}
            {% if current_page.has_next %}
                $('#next-page').attr('href', "{% url 'app:showuser' %}?show={{ showuser.pk }}&page={{ current_page.next_page_number }}")

            {% endif %}
        })


    </script>

{% endblock %}

templates/user/signsuccess.html
{% extends 'base/base.html' %}


{% block title %}

{% endblock %}


{% block style %}
<style>
.register-result{
    margin-left: 10%;
    width: 80%;
    background-color: white;
    padding-top: 5%;
    padding-bottom: 10%;
}
</style>
{% endblock %}


{% block body %}
{% if result %}
<div class="text-center register-result">
    <img src="/media/image/success.jpg">
    <h2>注册成功！5秒后跳转至<a href="{% url 'app:login' %}">登录界面</a></h2>
    <script>
        setTimeout(function () {
            window.location.href = "{% url 'app:login' %}"
        }, 5000)
    </script>

</div>
{% endif %}
<div class="text-center register-result">
<img src="/media/image/failure2.jpg">
    <h2>注册失败！</h2>
    <div>
        <h3>再来一次 ----> <a href="{% url 'app:signup' %}">重新注册</a></h3>
        <h3>不注册了， 直接访问<a href="{% url 'app:index' %}">首页</a></h3>
    </div>
</div>
{% endblock %}

{% block script %}

{% endblock %}